
[workspace]
members = ["domain"]
resolver = "3"

[workspace.dependencies]
async-trait = "0.1"
garde = { version = "0.22", features = ["derive", "email"] }
rstest = "0.25"
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "macros",
  "derive",
  "uuid",
  "time",
] }
thiserror = "2"
time = { version = "0.3", features = ["serde", "macros"] }
uuid = { version = "1", features = ["v4", "serde"] }
