services:
  db:
    image: postgres:17
    container_name: todo_db
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo-password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
  redis:
    image: redis:8
    container_name: todo_redis
    ports:
      - "6379:6379"
