[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
domain = { path = "../domain" }
secrecy.workspace = true
sqlx.workspace = true
time.workspace = true
