[package]
name = "use_case"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
domain = { path = "../domain" }

[dev-dependencies]
anyhow.workspace = true
rstest.workspace = true
