[package]
name = "use_case"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
domain = { path = "../domain" }
secrecy.workspace = true
time.workspace = true
uuid.workspace = true
